#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignupForm
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="URI")]
	public partial class TestDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_User(tbl_User instance);
    partial void Updatetbl_User(tbl_User instance);
    partial void Deletetbl_User(tbl_User instance);
    #endregion
		
		public TestDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["URIConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TestDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_User> tbl_Users
		{
			get
			{
				return this.GetTable<tbl_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Users")]
	public partial class tbl_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _User_ID;
		
		private string _User_Fullname;
		
		private string _User_Email;
		
		private string _User_campus;
		
		private string _User_Department;
		
		private string _User_Degree;
		
		private string _User_session;
		
		private string _User_Enrollment;
		
		private string _User_loginID;
		
		private string _User_Password;
		
		private string _User_CreatedBY;
		
		private string _User_Createdon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IDChanging(long value);
    partial void OnUser_IDChanged();
    partial void OnUser_FullnameChanging(string value);
    partial void OnUser_FullnameChanged();
    partial void OnUser_EmailChanging(string value);
    partial void OnUser_EmailChanged();
    partial void OnUser_campusChanging(string value);
    partial void OnUser_campusChanged();
    partial void OnUser_DepartmentChanging(string value);
    partial void OnUser_DepartmentChanged();
    partial void OnUser_DegreeChanging(string value);
    partial void OnUser_DegreeChanged();
    partial void OnUser_sessionChanging(string value);
    partial void OnUser_sessionChanged();
    partial void OnUser_EnrollmentChanging(string value);
    partial void OnUser_EnrollmentChanged();
    partial void OnUser_loginIDChanging(string value);
    partial void OnUser_loginIDChanged();
    partial void OnUser_PasswordChanging(string value);
    partial void OnUser_PasswordChanged();
    partial void OnUser_CreatedBYChanging(string value);
    partial void OnUser_CreatedBYChanged();
    partial void OnUser_CreatedonChanging(string value);
    partial void OnUser_CreatedonChanged();
    #endregion
		
		public tbl_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Fullname", DbType="VarChar(50)")]
		public string User_Fullname
		{
			get
			{
				return this._User_Fullname;
			}
			set
			{
				if ((this._User_Fullname != value))
				{
					this.OnUser_FullnameChanging(value);
					this.SendPropertyChanging();
					this._User_Fullname = value;
					this.SendPropertyChanged("User_Fullname");
					this.OnUser_FullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Email", DbType="VarChar(50)")]
		public string User_Email
		{
			get
			{
				return this._User_Email;
			}
			set
			{
				if ((this._User_Email != value))
				{
					this.OnUser_EmailChanging(value);
					this.SendPropertyChanging();
					this._User_Email = value;
					this.SendPropertyChanged("User_Email");
					this.OnUser_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_campus", DbType="VarChar(50)")]
		public string User_campus
		{
			get
			{
				return this._User_campus;
			}
			set
			{
				if ((this._User_campus != value))
				{
					this.OnUser_campusChanging(value);
					this.SendPropertyChanging();
					this._User_campus = value;
					this.SendPropertyChanged("User_campus");
					this.OnUser_campusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Department", DbType="VarChar(50)")]
		public string User_Department
		{
			get
			{
				return this._User_Department;
			}
			set
			{
				if ((this._User_Department != value))
				{
					this.OnUser_DepartmentChanging(value);
					this.SendPropertyChanging();
					this._User_Department = value;
					this.SendPropertyChanged("User_Department");
					this.OnUser_DepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Degree", DbType="VarChar(50)")]
		public string User_Degree
		{
			get
			{
				return this._User_Degree;
			}
			set
			{
				if ((this._User_Degree != value))
				{
					this.OnUser_DegreeChanging(value);
					this.SendPropertyChanging();
					this._User_Degree = value;
					this.SendPropertyChanged("User_Degree");
					this.OnUser_DegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_session", DbType="VarChar(50)")]
		public string User_session
		{
			get
			{
				return this._User_session;
			}
			set
			{
				if ((this._User_session != value))
				{
					this.OnUser_sessionChanging(value);
					this.SendPropertyChanging();
					this._User_session = value;
					this.SendPropertyChanged("User_session");
					this.OnUser_sessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Enrollment", DbType="VarChar(50)")]
		public string User_Enrollment
		{
			get
			{
				return this._User_Enrollment;
			}
			set
			{
				if ((this._User_Enrollment != value))
				{
					this.OnUser_EnrollmentChanging(value);
					this.SendPropertyChanging();
					this._User_Enrollment = value;
					this.SendPropertyChanged("User_Enrollment");
					this.OnUser_EnrollmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_loginID", DbType="VarChar(50)")]
		public string User_loginID
		{
			get
			{
				return this._User_loginID;
			}
			set
			{
				if ((this._User_loginID != value))
				{
					this.OnUser_loginIDChanging(value);
					this.SendPropertyChanging();
					this._User_loginID = value;
					this.SendPropertyChanged("User_loginID");
					this.OnUser_loginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Password", DbType="VarChar(50)")]
		public string User_Password
		{
			get
			{
				return this._User_Password;
			}
			set
			{
				if ((this._User_Password != value))
				{
					this.OnUser_PasswordChanging(value);
					this.SendPropertyChanging();
					this._User_Password = value;
					this.SendPropertyChanged("User_Password");
					this.OnUser_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_CreatedBY", DbType="VarChar(50)")]
		public string User_CreatedBY
		{
			get
			{
				return this._User_CreatedBY;
			}
			set
			{
				if ((this._User_CreatedBY != value))
				{
					this.OnUser_CreatedBYChanging(value);
					this.SendPropertyChanging();
					this._User_CreatedBY = value;
					this.SendPropertyChanged("User_CreatedBY");
					this.OnUser_CreatedBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Createdon", DbType="VarChar(50)")]
		public string User_Createdon
		{
			get
			{
				return this._User_Createdon;
			}
			set
			{
				if ((this._User_Createdon != value))
				{
					this.OnUser_CreatedonChanging(value);
					this.SendPropertyChanging();
					this._User_Createdon = value;
					this.SendPropertyChanged("User_Createdon");
					this.OnUser_CreatedonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
